src/core/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^manager/', include('manager.urls')),

    # Core URLS
    url(r'^$', 'dashboard.views.index', name='index'),
    url(r'^login/$', 'core.views.login', name='login'),
    url(r'^logout/$', 'core.views.logout', name='logout'),
]

src/manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', 'manager.views.index', name='manager_index'),
    
    url(r'^system/new/$', 'manager.views.system', name='new_system'),
    url(r'^system/(?P<system_id>\d+)/$', 'manager.views.system', name='edit_system'),

    url(r'^indcident/new/$', 'manager.views.incident', name='new_incident'),
    url(r'^note/(?P<incident_id>\d+)/close/$', 'manager.views.close_incident', name='close_incident'),
    url(r'^system/(?P<incident_id>\d+)/$', 'manager.views.incident', name='edit_incident'),

    url(r'^note/(?P<incident_id>\d+)/$', 'manager.views.add_new_note', name='add_new_note'),

]

src/core/models.py
from django.db import models
from django.contrib.auth.models import User

def status_choices():
	return (
		('operational', 'Operational'),
		('partial_outage', 'Partial Outage'),
		('major_outage', 'Major Outage'),
		('scheduled_release','Scheduled Release'),
	)

class System(models.Model):
	name = models.CharField(max_length=100)
	description = models.TextField(null=True, blank=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return u'%s' % (self.name)

	def open_incidents(self):
		return Incident.objects.filter(system=self, closed__isnull=True)

class Note(models.Model):
	text = models.TextField()
	posted = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-posted']

	def __unicode__(self):
		return u'Note: %s' % (self.posted)

class Incident(models.Model):
	system = models.ForeignKey(System)
	status = models.CharField(max_length=100, choices=status_choices())
	notes = models.ManyToManyField(Note)

	started = models.DateTimeField(null=True, blank=True)
	closed = models.DateTimeField(null=True, blank=True)
	user = models.ForeignKey(User)

	class Meta:
		ordering = ['-started']

	def __unicode__(self):
		return u'%s %s' % (self.system.name, self.status)


class Subscriber(models.Model):
	email_address = models.EmailField(unique=True)
	first_name = models.CharField(max_length=200)
	last_name = models.CharField(max_length=200)
	confirmation_code = models.CharField(max_length=200, null=True, blank=True)
	confirmed = models.BooleanField(default=False)

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)

src/manager/models.py
from django.db import models

# Create your models here.

src/manager/forms.py
from django import forms
from core import models

class NewSystem(forms.ModelForm):

	class Meta:
		model = models.System
		exclude = ()

class Incident(forms.ModelForm):

	class Meta:
		model = models.Incident
		exclude = ('notes', 'user', 'started', 'closed')

class Note(forms.ModelForm):

	class Meta:
		model = models.Note
		fields = ('text',)

src/manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.utils import timezone

from core import models
from manager import forms

@staff_member_required
def index(request):
	
	template = 'manager/index.html'
	context = {
		'systems': models.System.objects.all(),
		'current_incidents': models.Incident.objects.filter(closed__isnull=True),
		'past_incidents': models.Incident.objects.filter(closed__isnull=False),
	}
	return render(request, template, context)

@staff_member_required
def system(request, system_id=None):

	if system_id:
		system = get_object_or_404(models.System, pk=system_id)
		form = forms.NewSystem(instance=system)
	else:
		form = forms.NewSystem()
		system = None

	if request.POST:
		if system:
			form = forms.NewSystem(request.POST, instance=system)
		else:
			form = forms.NewSystem(request.POST)

		if form.is_valid():
			new_system = form.save()
			if system:
				message = 'System updated.'
			else:
				message = 'System created.'

			messages.add_message(request, messages.ERROR, message)
			return redirect(reverse('manager_index'))

	template = 'manager/system_new.html'
	context = {
		'form': form,
	}
	return render(request, template, context)

@staff_member_required
def incident(request, incident_id=None):

	if incident_id:
		incident = get_object_or_404(models.Incident, pk=incident_id)
		form = forms.Incident(instance=incident)
	else:
		incident = None
		form = forms.Incident()

	if request.POST:
		if incident_id:
			form = forms.Incident(request.POST, instance=insident)
		else:
			form = forms.Incident(request.POST)

		if form.is_valid():
			saved_incident = form.save(commit=False)
			saved_incident.user = request.user
			saved_incident.save()

			if incident_id:
				message = 'Incident updated.'
			else:
				note = request.POST.get('note')
				if note:
					new_note = models.Note(text=note)
					new_note.save()
					saved_incident.notes.add(new_note)
					saved_incident.started = timezone.now()
					saved_incident.save()

				message = 'Incident created.'

			messages.add_message(request, messages.ERROR, message)
			return redirect(reverse('manager_index'))

	template = 'manager/incident.html'
	context = {
		'form': form,
	}
	return render(request, template, context)

@staff_member_required
def add_new_note(request, incident_id):
	incident = get_object_or_404(models.Incident, pk=incident_id)
	form = forms.Note()

	if request.POST:
		form = forms.Note(request.POST)

		if form.is_valid():
			new_note = form.save()
			incident.notes.add(new_note)

			messages.add_message(request, messages.SUCCESS, 'Note added to incident')
			return redirect(reverse('manager_index'))

	template = 'manager/note.html'
	context = {
		'incident': incident,
		'form': form,
	}
	return render(request, template, context)

@staff_member_required
def close_incident(request, incident_id):
	incident = get_object_or_404(models.Incident, pk=incident_id)
	form = forms.Note()

	if request.POST:
		form = forms.Note(request.POST)

		if form.is_valid():
			new_note = form.save()
			incident.notes.add(new_note)
			incident.closed = timezone.now()
			incident.save()

			messages.add_message(request, messages.SUCCESS, 'Note added to incident')
			return redirect(reverse('manager_index'))

	template = 'manager/close_incident.html'
	context = {
		'incident': incident,
		'form': form,
	}
	return render(request, template, context)

src/manager/templates/manager/close_incident.html
{% extends "base.html" %}
{% load materialize %}

{% block body %}
  <div class="row">
    <form class="col s12" method="POST">
    {% csrf_token %}
      <div class="row">
    	<div class="col s12">
    		<div class="card-panel">
    			<h4>Close {{ incident.system.name }} Incident</h4>
			        <div class="input-field col s12">
			        Closing Note Text
			        <textarea class="validate materialize-textarea" cols="40" id="id_text" name="text" rows="10"></textarea>
			        </div>
		        <br /><br />
		        <button class="waves-effect waves-light btn" type="submit">Submit</button>
		        <a class="waves-effect waves-light btn red darken-3" href="{% url 'manager_index' %}">Cancel</a>
		      </div>
		    </div>
	    </div>
    </form>
  </div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(document).ready(function() {
    $('select').material_select();
});
</script>
{% endblock extrajs %}

src/manager/templates/manager/incident.html
{% extends "base.html" %}
{% load materialize %}

{% block body %}
  <div class="row">
    <form class="col s12" method="POST">
    {% csrf_token %}
      <div class="row">
    	<div class="col s12">
    		<div class="card-panel">
    			<h4>New System</h4>
			        <div class="input-field col s4">
			        {{ form.system.label }}
			        {{ form.system }}
			        </div>
			        <div class="input-field col s4">
			        {{ form.status.label }}
			        {{ form.status }}
			        </div>
			        <div class="input-field col s4">
			        {{ form.started.label }}
			        <input id="id_started" name="started" type="date" class="date">
			        </div>
			        <div class="input-field col s12">
			        Note
			        <textarea class="validate materialize-textarea" cols="40" id="id_note" name="note" rows="10"></textarea>
			        </div>
		        <br /><br />
		        <button class="waves-effect waves-light btn" type="submit">Submit</button>
		        <a class="waves-effect waves-light btn red darken-3" href="{% url 'manager_index' %}">Cancel</a>
		      </div>
		    </div>
	    </div>
    </form>
  </div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(document).ready(function() {
    $('select').material_select();
});
</script>
{% endblock extrajs %}

src/manager/templates/manager/index.html
{% extends "base.html" %}

{% block body %}
<h4>Manager</h4>
<a href="{% url 'new_system' %}" class="waves-effect waves-light btn">Add New System</a> &nbsp; <a href="{% url 'new_incident' %}" class="waves-effect waves-light btn red darken-4">Add New Incident</a>
<ul class="collection with-header">
	<li class="collection-header"><h4>System Status</h4></li>
	{% for system in systems %}
	<li class="collection-item"><div>{{ system.name }}<a class="secondary-content" href="{% url 'edit_system' system.pk %}">&nbsp;&nbsp;Edit</a><br /><i>
	{% if system.active %}
	{% if system.open_incidents %}{{ system.open_incidents.0.get_status_display }}{% else %}Operational{% endif %}
	{% else %}
	System Inactive
	{% endif %}
	</i></div></li>
	{% endfor %}
</ul>
{% if current_incidents %}
<h4>Current Incidents </h4>
{% for incident in current_incidents %}
	<div class="card">
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">{{ incident.system.name }}<i class="right">{{ incident.started }}</i></span>
      <p>{{ incident.system.name }} is currently experiencing an {{ incident.get_status_display }}.</p>
      <br />
      <span class="card-title activator grey-text text-darken-4">Notes</span>
      {% for note in incident.notes.all %}<p>{{ note.text|linebreaksbr|safe }}</p><p class="right-align">{{ note.posted }}<i class="fa fa-trash"></i></p>{% if not forloop.last %}<hr />{% endif %}{% endfor %}
      <a href="{% url 'add_new_note' incident.id %}" class="waves-effect waves-light btn">Add New Note</a>&nbsp;<a href="{% url 'close_incident' incident.id %}" class="waves-effect waves-light btn red darken-4">Close Incident</a>
    </div>
  </div>
{% endfor %}
{% endif %}

{% if past_incidents %}
<h4>Past Incidents</h4>
{% for incident in past_incidents %}
	<div class="card">
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">{{ incident.system.name }}<i class="right">{{ incident.started }}</i></span>
      <p>{{ incident.system.name }} is currently experiencing an {{ incident.get_status_display }}.</p>
      <br />
      <span class="card-title activator grey-text text-darken-4">Notes</span>
      {% for note in incident.notes.all %}<p>{{ note.text|linebreaksbr|safe }}</p><p class="right-align">{{ note.posted }}</p>{% if not forloop.last %}<hr />{% endif %}{% endfor %}
    </div>
  </div>
{% endfor %}
{% endif %}
{% endblock body %}

src/manager/templates/manager/note.html
{% extends "base.html" %}
{% load materialize %}

{% block body %}
  <div class="row">
    <form class="col s12" method="POST">
    {% csrf_token %}
      <div class="row">
    	<div class="col s12">
    		<div class="card-panel">
    			<h4>New Note for {{ incident.system.name }} Incident</h4>
			        <div class="input-field col s12">
			        Note Text
			        <textarea class="validate materialize-textarea" cols="40" id="id_text" name="text" rows="10"></textarea>
			        </div>
		        <br /><br />
		        <button class="waves-effect waves-light btn" type="submit">Submit</button>
		        <a class="waves-effect waves-light btn red darken-3" href="{% url 'manager_index' %}">Cancel</a>
		      </div>
		    </div>
	    </div>
    </form>
  </div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(document).ready(function() {
    $('select').material_select();
});
</script>
{% endblock extrajs %}

src/manager/templates/manager/system_new.html
{% extends "base.html" %}
{% load materialize %}

{% block body %}
  <div class="row">
    <form class="col s12" method="POST">
    {% csrf_token %}
      <div class="row">
    	<div class="col s12">
    		<div class="card-panel">
    			<h4>New System</h4>
		        <div class="input-field">
		        	{{ form.name|as_material:"s12" }}
		        	{{ form.description|as_material:"s12" }}
		        	{{ form.active|as_material:"s12" }}
		        </div>
		        <br /><br />
		        <button class="waves-effect waves-light btn" type="submit">Submit</button>
		        <a class="waves-effect waves-light btn red darken-3" href="{% url 'manager_index' %}">Cancel</a>
		      </div>
		    </div>
	    </div>
    </form>
  </div>
{% endblock %}